package by.bsuir.iit.aipos.domain.http_parameters;

public enum HeaderField {

    DATE, PRAGMA,
    AUTHORIZATION, FROM, IF_MODIFIED_SINCE, REFERER, USER_AGENT, LOCATION,
    ALLOW, CONTENT_ENCODING, CONTENT_LENGTH, CONTENT_TYPE, EXPIRES, LAST_MODIFIED
}
