package by.bsuir.iit.aipos.domain.http_parameters;

public enum ResponseStatus {
    OK, CREATED, ACCEPTED, NO_CONTENT,

    MOVED_PERMANENTLY, FOUND, NOT_MODIFIED,

    BAD_REQUEST, UNAUTHORIZED, FORBIDDEN, NOT_FOUND,

    INTERNAL_SERVER_ERROR, NOT_IMPLEMENTED, BAD_GATEWAY, SERVICE_UNAVAILABLE;
}
